name: IP Optimizer
on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '0 21 * * *'  # UTC 21:00 = 北京时间 5:00
    - cron: '0 9 * * *'   # UTC 9:00 = 北京时间 17:00

jobs:
  optimize:
    runs-on: ubuntu-latest
    env:
      MODE: TCP               # 可修改：TCP/ICMP
      PORT: 443               # 可修改端口
      RTT_RANGE: "40~250"     # 延迟范围(ms)
      LOSS_MAX: 10            # 最大丢包率(%)
      DOWNLOAD_MIN: 1.00      # 最低下载速度(MB/s)
      IP_COUNT: 1000          # 随机生成 IP 数量
      THREADS: 50             # 线程数
      SPEED_URL: "https://speed.cloudflare.com/__down?bytes=10000000" # 测速链接
      CLOUDFLARE_IPS: "https://www.cloudflare.com/ips-v4" # Cloudflare IP 段

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests numpy

    - name: Run IP Optimizer
      run: python ip_optimizer.py

    - name: Commit results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add results/
        git commit -m "Update optimized IPs"
        git push
